name: Automated Release to GH
on:
  push:
    branches:
      - "main"
  release:
    types: [ published ]
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  create-release:
    needs: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.4 [GraphCommerce >= 8.0.0] 27 May 2024
          tag_name: 1.0.4
          body: |-
            - **Feature**: Add Cms service links component with MUI icons [#4]
            - **Feature**: Add CMS text row renderer component [#3]
            - **Feature**: Add Category Hero Nav to category landing pages [#2]
            - **Feature**: Add RichText AST description to category pages [#1]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}